% This script will open and display a mesh video 
% with data generated by the FiLM-Scope
% This allows the user to interact with the data as it plays 

% Select a filename to open and run
path_to_data = ""
load(path_to_data + "/matlab_video_files/skull_tool_video.mat")
%load(path_to_data + "/matlab_video_files/knuckle_video.mat")

%%
locations = double(locations);
z_scale = 1;

X = locations(:, :, :, 1);
Y = locations(:, :, :, 2);
Z = locations(:, :, :, 3) * z_scale;

v = locations(:, :, :, 4);
locations(:, :, :, 4) = (v - min(v, [], "all")) ./ (max(v, [], "all") - min(v, [], "all"));


frame = 1;
minx = min(X(:));
maxx = max(X(:));
miny = min(Y(:));
maxy = max(Y(:));
minz = min(Z(:));
maxz = max(Z(:));
minc = min(v(:));
maxc = max(v(:));
X = squeeze(locations(frame, :, :, 1));
Y = squeeze(locations(frame, :, :, 2));
Z = squeeze(locations(frame, :, :, 3));
values = squeeze(locations(frame, :, :, 4));
h = mesh(X, Y, Z, values);
axis([minx, maxx, miny, maxy, minz, maxz]);
daspect([1 1 1])
set(gcf, "Color", "k");
set(gca, 'Color', 'k');
set(gca, 'XColor', 'w', 'YColor', 'w', 'ZColor', 'w');
%caxis([minc maxc]);
grid off;
hold on;
colormap 'gray';

%%
while 1
    Z = squeeze(locations(frame, :, :, 3));
    values = squeeze(locations(frame, :, :, 4));
    set(h, 'ZData', Z);
    set(h, 'CData', values);
    pause(0.05);

    frame = mod(frame + 1, size(locations, 1)) + 1;
end